{{- range .Values.extractors }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | replace "-" "" }}
  labels:
    {{- include "labels" (dict "name" .name "component" "extractor" "global" $) | nindent 4 }}
spec:
  ports:
    - port: 9501
  selector:
    {{- include "labels" (dict "name" .name "component" "extractor" "global" $) | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | replace "-" "" }}
  labels:
    {{- include "labels" (dict "name" .name "component" "extractor" "global" $) | nindent 4 }}
spec:
  replicas: {{ default .replicas 1 }}
  selector:
    matchLabels:
      {{- include "labels" (dict "name" .name "component" "extractor" "global" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" (dict "name" .name "component" "extractor" "global" $) | nindent 8 }}
    spec:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: extractor
          image: {{ .image }}

          command: ['/bin/bash', '-c']
          args:
            - |-
              indexify-extractor join-server \
              --coordinator-addr coordinator:8950 \
              --ingestion-addr api:8900 \
              --advertise-addr $(hostname | cut -d"-" -f1):9501 \
              --listen-port 9501

          env:
            {{- include "blobStore.env" $.Values | nindent 12 }}
{{- end }}
